### DISCUSSION TITLE
AFFiNE on CasaOs?

### DISCUSSION THREAD

**Discussion by ronaldohoch** [toeverything/AFFiNE#10205] [Q&A]
Hi guys, has anyone here managed to install AFFiNE on CasaOs?

https://docs.affine.pro/docs/self-host-affine

It has a step-by-step guide, using docker-compose, but I still can't get it to work.
I've been fixing the problems via the container logs, but I haven't been able to get it to connect to Affine's postgres.

edit:

This is my docker-compos with some changes with help of chatgpt:

Docker-compose:
```yml  
name: affine
services:
  affine:
    cpu_shares: 90
    container_name: affine_server
    depends_on:
      affine_migration:
        condition: service_completed_successfully
      affine_postgresql:
        condition: service_healthy
      affine_redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - DATABASE_URL=postgresql://affine_user:affine_password@affine_postgresql:5432/affine_db
      - REDIS_SERVER_HOST=affine_redis
    image: ghcr.io/toeverything/affine-graphql:stable
    ports:
      - "3010:3010"
    restart: unless-stopped
    volumes:
      - /mnt/seagate2t/affine/storage:/root/.affine/storage
      - /mnt/seagate2t/affine/config:/root/.affine/config
    networks:
      - affine_network

  affine_migration:
    cpu_shares: 90
    command: ["sh", "-c", "sleep 10 && node ./scripts/self-host-predeploy.js"]
    container_name: affine_migration_job
    depends_on:
      affine_postgresql:
        condition: service_healthy
      affine_redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - DATABASE_URL=postgresql://affine_user:affine_password@affine_postgresql:5432/affine_db
      - REDIS_SERVER_HOST=affine_redis
    image: ghcr.io/toeverything/affine-graphql:stable
    restart: unless-stopped
    volumes:
      - /mnt/seagate2t/affine/storage:/root/.affine/storage
      - /mnt/seagate2t/affine/config:/root/.affine/config
    networks:
      - affine_network

  affine_postgresql:
    cpu_shares: 90
    container_name: affine_postgresql
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - POSTGRES_DB=affine_db
      - POSTGRES_USER=affine_user
      - POSTGRES_PASSWORD=affine_password
      - POSTGRES_INITDB_ARGS=--data-checksums
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U affine_user -d affine_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /mnt/seagate2t/affine/db:/var/lib/postgresql/data
    networks:
      - affine_network

  affine_redis:
    cpu_shares: 90
    container_name: affine_redis
    deploy:
      resources:
        limits:
          memory: 15907M
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    image: redis:latest
    restart: unless-stopped
    networks:
      - affine_network

networks:
  affine_network:
    driver: bridge

```

The log from container:

```
PrismaClientInitializationError: 

Invalid `prisma.runtimeConfig.findMany()` invocation:

Can't reach database server at `affine_postgresql:5432`

Please make sure your database server is running at `affine_postgresql:5432`.

    at $n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7615)

    at $n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:6623)

    at $n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6307)

    at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9633)

    at async Runtime.upgradeDB (file:///app/dist/base/runtime/service.js:194:36)

    at async Runtime.onModuleInit (file:///app/dist/base/runtime/service.js:103:9)

    at async Promise.all (index 0)

    at async callModuleInitHook (/app/node_modules/@nestjs/core/hooks/on-module-init.hook.js:43:5)

    at async NestApplication.callInitHook (/app/node_modules/@nestjs/core/nest-application-context.js:234:13)

    at async NestApplication.init (/app/node_modules/@nestjs/core/nest-application.js:100:9) {

  clientVersion: '5.22.0',

  errorCode: undefined

}

Node.js v20.18.1
```

**Comment by Novapixel1010** [comment]
Is it possible your database is failing to start. You could try starting just the database and see that it is at least starting. Or you could use an external database at least that is what I usually do.

**Reply by ronaldohoch** [reply]
I made it work, i don't remember how exactly ><

```yaml
name: affine
services:
  affine:
    cpu_shares: 90
    command:
      - sh
      - -c
      - node ./scripts/self-host-predeploy && node ./dist/index.js
    container_name: affine-app
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: 15907M
        reservations:
          memory: "1073741824"
    environment:
      - AFFINE_ADMIN_EMAIL=affine@acme.sh
      - AFFINE_ADMIN_PASSWORD=affine
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - NODE_OPTIONS=--import=./scripts/register.js
      - REDIS_SERVER_HOST=redis
    hostname: affine-app
    image: ghcr.io/toeverything/affine-graphql:stable
    labels:
      icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/icon.svg
    logging:
      driver: json-file
      options:
        max-size: 1000m
    ports:
      - mode: ingress
        target: 3010
        published: "3010"
        protocol: tcp
      - mode: ingress
        target: 5555
        published: "5555"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/affine/config
        target: /root/.affine/config
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/affine/storage
        target: /root/.affine/storage
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    networks:
      - affine
    privileged: false
  postgres:
    cpu_shares: 90
    container_name: affine-postgres
    deploy:
      resources:
        limits:
          memory: 15907M
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=affine
      - POSTGRES_PASSWORD=affine
      - POSTGRES_USER=affine
    hostname: affine-postgres
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U affine
      timeout: 5s
      interval: 10s
      retries: 5
    image: postgres:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/icon.svg
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/affine/postgres
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    command: []
    networks:
      - affine
    privileged: false
  redis:
    cpu_shares: 90
    container_name: affine-redis
    deploy:
      resources:
        limits:
          memory: 15907M
    hostname: affine-redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      timeout: 5s
      interval: 10s
      retries: 5
    image: redis:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/icon.svg
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/affine/redis
        target: /data
        bind:
          create_host_path: true
    ports: []
    devices: []
    cap_add: []
    command: []
    environment: []
    networks:
      - affine
    privileged: false
networks:
  affine:
    name: affine
x-casaos:
  architectures:
    - arm64
    - amd64
  author: Cp0204
  category: Documents
  description:
    en_us: A privacy-focused, local-first, open-source, and ready-to-use alternative
      for Notion & Miro. One hyper-fused platform for wildly creative minds.
      AFFiNE is a next-gen knowledge base that brings planning, sorting and
      creating all together. Privacy first, open-source, customizable and ready
      to use.
    zh_cn: AFFiNE 是一个注重隐私、本地优先、开源且即时可用的 Notion 和 Miro
      替代方案。这是一个专为狂野创意人士打造的超融合平台。AFFiNE
      是一个下一代知识库，它将计划、分类和创建融为一体。隐私至上，开源，可定制，开箱即用。
  developer: toeverything
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/icon.svg
  index: /
  is_uncontrolled: false
  main: affine
  port_map: "3010"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/screenshot-1.jpg
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/screenshot-2.jpg
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/screenshot-2.jpg
  store_app_id: affine
  tagline:
    en_us: Open source alternative to Notion and Miro
    zh_cn: Notion 和 Miro 的开源替代品
  thumbnail: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/affine/thumbnail.png
  tips:
    before_install:
      en_us: >
        The application can not be opened immediately at the first launch, it
        takes about 10 minutes to initialize, please be patient.


        Default username and password:


        **AFFINE_ADMIN_EMAIL**: `affine@acme.sh`

        **AFFINE_ADMIN_PASSWORD**: `affine`


        **Please change it before installation, changes may not take effect after initialization** and you need to remove the configuration file manually. `/DATA/AppData/affine`
      zh_cn: |
        应用首次启动无法立即打开，大约需要10分钟初始化，请耐心等待。

        默认用户名和密码：

        **AFFINE_ADMIN_EMAIL**: `affine@acme.sh`
        **AFFINE_ADMIN_PASSWORD**: `affine`

        **请在安装前修改，初始化后修改可能无法生效**，需要手动移除配置文件。`/DATA/AppData/affine`
  title:
    custom: ""
    en_us: AFFiNE

```

**Comment by HSinghHira** [comment]
Here: https://github.com/HSinghHira/ZimaAppStore

**Comment by constgen** [comment]
This works in ZimaOS

```yml
networks:
  affine_network:
    name: affine_affine_network
    driver: bridge
    ipam: {}
    external: false
services:
  affine:
    command: null
    container_name: affine
    depends_on:
      affine_migration:
        condition: service_completed_successfully
        required: true
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: 4GB
          cpus: "2"
        reservations:
          memory: 256MB
          cpus: "0.00"
      placement: {}
    entrypoint: null
    environment:
      DATABASE_URL: postgresql://affine@postgres:5432/affine
      REDIS_SERVER_HOST: redis
    image: ghcr.io/toeverything/affine:stable
    labels:
      icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.affine/assets/icon.png
    networks:
      - affine_network
    ports:
      - mode: ingress
        target: 3010
        published: "3010"
        protocol: tcp
    restart: unless-stopped
    stop_grace_period: 40s
    volumes:
      - type: bind
        source: /DATA/AppData/affine/storage
        target: /root/.affine/storage
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/affine/config
        target: /root/.affine/config
        bind:
          create_host_path: true
  affine_migration:
    command:
      - sh
      - -c
      - node ./scripts/self-host-predeploy.js
    container_name: affine_migration
    depends_on:
      postgres:
        condition: service_healthy
        required: true
      redis:
        condition: service_healthy
        required: true
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: "1.00"
        reservations:
          memory: 256MB
          cpus: "0.00"
      placement: {}
    entrypoint: null
    environment:
      AFFINE_INDEXER_ENABLED: "false"
      DATABASE_URL: postgresql://affine@postgres:5432/affine
      REDIS_SERVER_HOST: redis
    image: ghcr.io/toeverything/affine:stable
    labels:
      icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.affine/assets/icon.png
    networks:
      - affine_network
    restart: no
    stop_grace_period: 40s
    volumes:
      - type: bind
        source: /DATA/AppData/affine/storage
        target: /root/.affine/storage
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/affine/config
        target: /root/.affine/config
        bind:
          create_host_path: true
  postgres:
    command: null
    container_name: affine_postgres
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: "1.00"
        reservations:
          memory: 256MB
          cpus: "0.00"
      placement: {}
    entrypoint: null
    environment:
      POSTGRES_DB: affine
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "'--data-checksums'"
      POSTGRES_USER: affine
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U affine -d affine
      timeout: 5s
      interval: 10s
      retries: 5
    image: pgvector/pgvector:pg16
    labels:
      icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.affine/assets/icon.png
    networks:
      - affine_network
    restart: unless-stopped
    stop_grace_period: 1m0s
    volumes:
      - type: bind
        source: /DATA/AppData/affine/postgres
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
  redis:
    command: null
    container_name: affine_redis
    deploy:
      resources:
        limits:
          memory: 256MB
          cpus: "0.50"
        reservations:
          memory: 256MB
          cpus: "0.00"
      placement: {}
    entrypoint: null
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
      interval: 10s
      retries: 5
    image: redis:7-alpine
    labels:
      icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.affine/assets/icon.png
    networks:
      - affine_network
    restart: unless-stopped
    stop_grace_period: 40s
    volumes: []
x-casaos:
  hostname: ""
  icon: https://Zimaos.hsinghhira.me/apps/com.hiraappstore.affine/assets/icon.png
  id: com.hiraappstore.affine
  index: /
  is_uncontrolled: false
  main: affine
  port_map: "3010"
  repo_id: com.hiraappstore.zimaappstore
  scheme: http
  store_app_id: affine
  title:
    custom: AFFiNE
    en_US: AFFiNE
```
