### DISCUSSION TITLE
How to make AI with self-hosted deployment of v0.20 work

### DISCUSSION THREAD

**Discussion by hnykda** [toeverything/AFFiNE#10549] [Show and tell]
I wasn't sure if I can make this work, but voila, it works. I am grateful for Affine and the team behind it, thanks a lot!

What I needed to do was to add this to the `affine.ts`, set the `COPILOT_OPENAI_API_KEY` env variable to my OpenAI API Key, and voila, it just works:

```
/* Copilot Plugin */
AFFiNE.use('copilot', {
  openai: {
    apiKey: process.env.COPILOT_OPENAI_API_KEY
  },
})
```

in my specific case, I have a docker-compose deployment via coolify, so with this config:

```
services:
  affine:
    image: 'ghcr.io/toeverything/affine-graphql:stable'
    command:
      - sh
      - '-c'
      - 'node ./scripts/self-host-predeploy && node ./dist/index.js'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - './data/config:/root/.affine/config'
      - './data/storage:/root/.affine/storage'
    logging:
      driver: json-file
      options:
        max-size: 1000m
    environment:
      - SERVICE_FQDN_AFFINE_3010
      - NODE_OPTIONS=--import=./scripts/register.js
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - 'DATABASE_URL=postgres://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres:5432/${POSTGRES_DB:-affine}'
      - NODE_ENV=production
      - AFFINE_SERVER_HOST=$SERVICE_FQDN_AFFINE
      - AFFINE_SERVER_EXTERNAL_URL=$SERVICE_FQDN_AFFINE
      - 'MAILER_HOST=${MAILER_HOST}'
      - 'MAILER_PORT=${MAILER_PORT}'
      - 'MAILER_USER=${MAILER_USER}'
      - 'MAILER_PASSWORD=${MAILER_PASSWORD}'
      - 'MAILER_SENDER=${MAILER_SENDER}'
      - COPILOT_OPENAI_API_KEY=${COPILOT_OPENAI_API_KEY}
    healthcheck:
      test:
        - CMD-SHELL
        - "bash -c ':> /dev/tcp/127.0.0.1/3010' || exit 1"
      interval: 5s
      timeout: 20s
      retries: 3
  redis:
    image: redis
    volumes:
      - 'affine-redis-data:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - '--raw'
        - incr
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: 'postgres:16'
    volumes:
      - 'affine-postgres-data:/var/lib/postgresql/data'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'POSTGRES_DB=${POSTGRES_DB:-affine}'
      - PGDATA=/var/lib/postgresql/data/pgdata
```

and then the file where I added the above is under `./data/config/affine.js`
