### DISCUSSION TITLE
AI for selfhost

### DISCUSSION THREAD

**Discussion by forehalo** [toeverything/AFFiNE#11722] [General]
> There are too many questions regarding AFFiNE AI support for selfhost instances and some of them are outdated.
> Let's make this one as the official QA and progress tracking for all the concerns.
> I will pin this on top of issues panel, the old ones or new comings will be closed directly and leave a ref to this issue. 

## Progress

- [ ] unbind actions with specified models
- [ ] support my own keys in admin panel
- [ ] support custom providers(ollama, deepseek, ...)
- [ ] more...

**Comment by forehalo** [comment]
## Can I enable the AI in an unofficial way now in my instance?

The answer is yes.

### Steps for those using provided compose file:

**1. create a JSON config at `${CONFIG_LOCATION}/config.json`**

> If you are using an editor that supports JSON lsp, the "$schema" field with provide you fully commented fields auto-complete

```json
{
  "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
  "copilot": {
    "enabled": true,
    "providers.openai": {
      "apiKey": "your key",
      "baseUrl": "open-ai-compatitable.example.com"
    }
  }
}
```

**2. restart your host**

```bash
docker compose up -d
```

### Steps for custom deployment:

**1. create a JSON config** 

```json
{
  "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
  "copilot": {
    "enabled": true,
    "providers.openai": {
      "apiKey": "your key",
    }
  }
}
```

**2. Mount or Copy the config file to your instance**

**3. import the config**

```bash
node --import ./scripts/register.js ./dist/data/index.js import-config ./path/to/config.json
```

**4. restart your host**

**Reply by losanglekk** [reply]
I try to set up today but get  import-config not found issue. any ideas?

**Reply by forehalo** [reply]
pull the latest image

**Reply by D3m0cr1tusGR** [reply]
I tried this configuration to connect to my ollama server but it didn't work

```json
{
        "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
        "copilot": {
                "enabled": true,
                "providers.openai": {
                        "apiKey": "ollama",
                        "baseUrl": "http://IP:11434/v1"
                }
        }
}
```

**Comment by ssly** [comment]
> ## Can I enable the AI in an unofficial way now in my instance?
> 现在能否以非官方方式在我的实例中启用 AI？
> The answer is yes.答案是肯定的。
> 
> ### Steps for those using provided compose file:
> **1. create a JSON config at `${CONFIG_LOCATION}/config.json`1. 在 `${CONFIG_LOCATION}/config.json` 创建一个 JSON 配置文件**
> 
> > If you are using an editor that supports JSON lsp, the "$schema" field with provide you fully commented fields auto-complete如果您使用的是支持 JSON lsp 的编辑器，"$schema"字段将为您提供带有完整注释的字段自动完成功能
> 
> {
>   "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
>   "copilot": {
>     "enabled": true,
>     "providers.openai": {
>       "apiKey": "your key",
>       "baseUrl": "open-ai-compatitable.example.com"
>     }
>   }
> }
> **2. restart your host  2. 重启主机**
> 
> docker compose up -d
> ### Steps for custom deployment:
> **1. create a JSON config1. 创建 JSON 配置文件**
> 
> {
>   "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
>   "copilot": {
>     "enabled": true,
>     "providers.openai": {
>       "apiKey": "your key",
>     }
>   }
> }
> **2. Mount or Copy the config file to your instance2. 将配置文件挂载或复制到您的实例**
> 
> **3. import the config  3. 导入配置**
> 
> node --import ./scripts/register.js ./dist/data/index.js import-config ./path/to/config.json
> **4. restart your host  4. 重启您的宿主**

How can I configure DeepSeek? How to set up the model. Moreover, in the 0.21.2 management panel, the AI function cannot be activated.

![Image](https://github.com/user-attachments/assets/7f95b54e-d6a9-49b4-b1c3-6ba95a22034e)

**Reply by forehalo** [reply]
That why I called the solution in https://github.com/toeverything/AFFiNE/issues/11691#issuecomment-2803699081 is "unofficial". to configure AI functionality in Admin panel is still work in progress.

Regarding using DeepSeek, it's concurrently not supported yet, but I think it will be available with AI admin panel together

**Comment by MrSquaare** [comment]
Hello!

Thanks for the tips for selfhosted instance

Will there be AI support for local workspace?

**Reply by forehalo** [reply]
You can only use simple actions in local workspace like random chat, translation. The actions with context awareness, for example embedding, can not be used with local workspaces, because the server doesn't know the content of your local workspace

**Comment by daydaya** [comment]
好像仍然有10次的使用限制，我使用自己的 API key 进行配置，并在openrouter后台看到了使用记录，但是affine中的AI仍然只能使用10次

**Reply by vladkor97** [reply]
Turn on unlimited AI for yourself in your admin panel

**Reply by daydaya** [reply]
Wow, it's really possible! In the account settings, click on modify, and you can see the options, thank you very much 🙏

**Reply by vladkor97** [reply]
You're welcome :)

**Reply by ssly** [reply]
> Wow, it's really possible! In the account settings, click on modify, and you can see the options, thank you very much 🙏哇，这真的可能！在账户设置中，点击修改，你可以看到选项，非常感谢 🙏

你使用的是什么模型，我这边这个管理员面板的 AI 按钮无法开启，是禁用状态

**Reply by Kosette** [reply]
@ssly 使用OpenAI兼容的API以及正确的apikey没有问题，服务启动时会检测API的可用性，可以查看日志。如果没有办法开启AI可能是配置有误。理论上还支持其他的AI provider，具有可用性可查看对应的源代码。

**Reply by zonbao** [reply]
请问，怎么更换掉系统原来的提示词。每次提问都带一大串自我介绍提示词

**Comment by boom404** [comment]
I created for myself a small server between Affine and Gemini or OpenRouter, who provides free API keys. Not sure if this allowed here in this chat.
My solution is implemented to start as normal docker container. "Ask AI" is working as expected 

https://github.com/boom404/affine-copilot-fix

**Reply by zonbao** [reply]
Excellent, I used your method. Successfully used the model of Gemini and openrouter on AFFiNE 0.21.4

**Reply by NorkzYT** [reply]
Edit:

Figured it out:
I forgot to run `node --import ./scripts/register.js   ./dist/data/index.js import-config /root/.affine/config/config.json` inside the docker container and then run `docker compose up -d --force-recreate`.

@boom404 

I am following your guide from your repo to be able to use OpenAI with the AFFINE version of 0.21.4 which is the latest stable version and  the connection is not working for some reason. Any help would be appreciated.

Below are all my files:

`/opt/docker/affine/.affine/self-host/config/config.json`:
```json
{
    "$schema": "https://github.com/toeverything/affine/releases/latest/download/config.schema.json",
    "server": {
        "name": "Affine"
    },
    "copilot": {
        "enabled": true,
        "providers.openai": {
            "apiKey": "my-not-exist-api-key",
            "baseUrl": "http://affine-copilot-fix:5000"
        }
    }
}
```

`docker-compose.yml`:
```yml
name: affine
services:
  affine-copilot-fix:
    container_name: affine-copilot-fix
    user: "1000:1000"
    build:
        context: ./affine-copilot-fix
        dockerfile: Dockerfile
    volumes:
        - ./logs:/app/src/logs
    env_file:
      - .env
    environment:
        - CREATE_LOG=True
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - OPENAI_BASE_URL=https://openrouter.ai/api/v1 # https://openrouter.ai/api/v1/
        - OPENAI_MODEL=openai/o4-mini # Or any openrouter model
    ports:
        - 5000:5000
    networks:
      - proxy

  affine:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_server
    ports:
      - '${PORT:-3010}:3010'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - /opt/docker/affine/.affine/self-host/storage:/root/.affine/storage
      - /opt/docker/affine/.affine/self-host/config:/root/.affine/config
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
    restart: unless-stopped
    networks:
      - proxy

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - /opt/docker/affine/.affine/self-host/storage:/root/.affine/storage
      - /opt/docker/affine/.affine/self-host/config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - proxy

  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - proxy  

  postgres:
    image: postgres:16
    container_name: affine_postgres
    volumes:
      - /opt/docker/affine/.affine/self-host/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
```
