### DISCUSSION TITLE
Self-Hosting: No way to create the first account

### DISCUSSION THREAD

**Discussion by romu70** [toeverything/AFFiNE#12755] [Q&A]
Hi. 
I've installed Affine on my Synology nas, using a set of Docker containers as described in the official docker compose script.

Everything seems to run fine, except...I can't create the first account. I enter the username, the login and the password, then I click on Continue.

After the first click, nothing appears at all. And if I click on Continue a second time, I get a strange thing:
- The email field has an "Invalid email address" error caption
- The password field has an "Invalid password..."

If I look at the dev tools (Firefox), I see this:
- In network, I see a call to "create-admin-user" and the response: "NS_ERROR_NET_RESET"
- In the console, I see this error: TypeError: NetworkError when attempting to fetch resource.

In the Affine container log, there is no specific error.

Any help would be great.

**Comment by fengmk2** [comment]
check https://docs.affine.pro/self-host-affine/install/after-installation the document.

If still have the issues, please reinstall with docker compose https://docs.affine.pro/self-host-affine/install/docker-compose-recommend

**Comment by romu70** [comment]
Thanks for your message @fengmk2, but it's exactly where is doesn't work on my server, if it wasn't clear enough.

Here is my docker compose file, I can't use directly the one provided by Affine because:
- My server runs some other services which are all declared in this single Docker compose file
- My server runs an old docker compose version (1.28.5) which doesn't provide the last features used in the Affine file

```
  postgres-15:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres-15:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: blablabla
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "<pg port>:5432"

  redis:
    image: redis:8.0.2-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data
    restart: always
    ports:
      - 6379:6379

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:stable-512a908
    volumes:
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    command: ["sh", "-c", "node ./scripts/self-host-predeploy.js"]
    environment:
      REDIS_SERVER_HOST: <my host IP>
      DATABASE_URL: "postgresql://affine:blablabla@<my host IP>:<pg port>/affine"
      AFFINE_INDEXER_ENABLED: "false"
    depends_on:
      - postgres-15
      - redis

  affine:
    image: ghcr.io/toeverything/affine-graphql:stable-512a908
    ports:
      - <affine port>:3010
    depends_on:
      redis:
        condition: service_started
      postgres-15:
        condition: service_started
      affine_migration:
        condition: service_started
    volumes:
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    environment:
      REDIS_SERVER_HOST: <my host IP>
      DATABASE_URL: "postgresql://affine:blablabla@<my host IP>:<pg port>/affine"
      AFFINE_INDEXER_ENABLED: "false"
    restart: always
```

What I see:
- The 3 containers start correctly
- The Affine migration container is stopped after a moment, which seems logical I presume
- The PG Affine DB is well populated
- There is even data in some tables like _data_migrations, _ai_prompt_messages, and some other, so no problem to access the DB from the Affine container

When:
- I connect to the Affine page for the first time: no error in the console.
- I enter the first user info and click continue and after a while:

<img width="548" alt="Screenshot 2025-06-09 at 10 05 27" src="https://github.com/user-attachments/assets/f3c33817-0e1f-4478-8e9e-1afa264f133a" />
