### ISSUE TITLE
​Blank page when using reverse proxy

### ISSUE THREAD

**Issue by oxypomme** [toeverything/AFFiNE#10460]
### What happened?

I just self-hosted AFFiNE and trying to use a reverse proxy to access it behind a domain name (`notes.oxyhome.lan`) using a local DNS.

I can access web version through port (`http://notes.oxyhome.lan:3010`), but when I try to access through Traefik (`http://notes.oxyhome.lan:80` or `https://notes.oxyhome.lan:443`) I get a blank page and every request to AFFiNE server failing with a 404 like this :
```
$ curl --verbose http://notes.oxyhome.lan:80/js/vendor.0bc91e77.js
* Connected to notes.oxyhome.lan (192.168.0.1) port 80
* using HTTP/2
> GET /js/vendor.0bc91e77.js HTTP/2
> Host: notes.oxyhome.lan
> User-Agent: curl/8.12.1
> Accept: */*
> 
* Request completely sent off
< HTTP/2 404 
< access-control-allow-origin: *
< content-type: application/json; charset=utf-8
< date: Thu, 27 Feb 2025 01:27:14 GMT
< etag: W/"..."
< x-powered-by: Express
< content-length: 43
< 
* Connection #0 to host notes.oxyhome.lan left intact
{"msg":"Cannot GET /js/vendor.0bc91e77.js"}
```

I added browser's logs and docker compose file, but feel free to ask for more precisions

## Expected behaviour

I should be able to get the files while using the reverse proxy, like I do with the port `3010` :

```
$ curl --verbose http://notes.oxyhome.lan:3010/js/vendor.0bc91e77.js
* Connected to notes.oxyhome.lan (192.168.0.1) port 3010
* using HTTP/1.x
> GET /js/vendor.0bc91e77.js HTTP/1.1
> Host: notes.oxyhome.lan:3010
> User-Agent: curl/8.12.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< X-Request-Id: allinone:http:adfac146-027f-48ad-bfe4-96160986ceee
< Accept-Ranges: bytes
< Cache-Control: public, max-age=0
< Last-Modified: Tue, 25 Feb 2025 06:04:32 GMT
< ETag: W/"..."
< Content-Type: application/javascript; charset=UTF-8
< Content-Length: 2729326
< Server-Timing: affine-server;dur=1.4637090000000001
< Date: Thu, 27 Feb 2025 01:35:40 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host notes.oxyhome.lan left intact
{ [3857 bytes data]
```

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [x] Yes

### Relevant log output

```shell
GET https://notes.oxyhome.lan/styles.169e6791.css net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/js/npm-rxjs.955bd098.js net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/js/npm-react.a4c6e395.js net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/js/9094.b7c56067.js net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/js/app.744d236a.js net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/js/npm-blocksuite.e142e76a.js net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/js/3029.e2f09b6c.js net::ERR_ABORTED 404 (Not Found)
GET https://notes.oxyhome.lan/manifest.json 404 (Not Found)
```

## `docker-compose.yaml`

<details>

```yaml
version: "3.8"
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_server
    depends_on:
      redis:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    ports:
      - 3010:3010
    volumes:
      - ./files/affine/storage:/root/.affine/storage
      - ./files/affine/config:/root/.affine/config
    env_file: .env
    restart: unless-stopped
    labels:
      traefik.docker.network: gateway-network
      traefik.http.services.nocodb.loadbalancer.server.port: 3010

      traefik.http.routers.affine_http.rule: Host(`notes.oxyhome.lan`)
      # this midlleware will redirect http to https, disabled to test if HTTPS was the issue
      # traefik.http.routers.affine_http.middlewares: redirect-to-https
      traefik.http.routers.affine_http.entrypoints: web

      traefik.http.routers.affine.rule: Host(`notes.oxyhome.lan`)
      traefik.http.routers.affine.entrypoints: websecure
      traefik.http.routers.affine.tls: true

      glance.name: Affine
      glance.icon: si:affine
      glance.url: https://notes.oxyhome.lan
      glance.id: affine
    networks:
      - gateway-network # The network connecting all the services to Traefik
      - db-network # The network connecting all the services to the database
      - default

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_migration_job
    volumes:
      - ./files/affine/storage:/root/.affine/storage
      - ./files/affine/config:/root/.affine/config
    command:
      - sh
      - -c
      - node ./scripts/self-host-predeploy.js
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    labels:
      glance.hide: true
    networks:
      - db-network
      - default

  redis:
    image: redis
    container_name: affine-redis
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    labels:
      glance.name: Redis
      glance.icon: si:redis
      glance.parent: affine
    networks:
      - default
networks:
  default: {}
  gateway-network:
    external: true
  db-network:
    external: true
x-dockge:
  urls:
    - https://notes.oxyhome.lan
```

</details>

## `.env`

```.env
REDIS_SERVER_HOST=redis
DATABASE_URL=postgresql://postgres:postgres@postgres:5432/affine
AFFINE_SERVER_HTTPS=true
AFFINE_SERVER_HOST=notes.oxyhome.lan
AFFINE_SERVER_EXTERNAL_URL=https://notes.oxyhome.lan:443
```
