### ISSUE TITLE
[Feature Request]: Self-hosting with Redis alternative

### ISSUE THREAD

**Issue by TheDidek** [toeverything/AFFiNE#11220]
### Description

As AFFiNE is being build as an open-source project, it would be great to official support for hosting it without Redis dependency or with some open-source Redis alternative like ValKey, DiceDB or KeyDB.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by forehalo** [comment]
redis is required component for internal job/cache/sync system.

**Comment by oilervoss** [comment]
I don't know when, but Affine has been totally transparent to use other redis implementations. I've been using valkey sucessfully. Just use the following [environment variables](https://docs.affine.pro/self-host-affine/references/environment-variables#redis) to point to your alternative redis instalation:
```yaml
  environment: 
    REDIS_SERVER_HOST: "192.168.0.211"  #your redis/valkey IP
    REDIS_SERVER_PORT: "6379" 
    REDIS_SERVER_USERNAME: "affine" #the redis/valkey user recorded in /etc/valkey/valkey.conf
    REDIS_SERVER_PASSWORD: "kjdkfjdjfdjfdjfadjfjdasf" #the redis/valkey user password recorded in /etc/valkey/valkey.conf
    REDIS_SERVER_DATABASE: 6 #the database number. Watch out that Affine will use five databases starting from this, i.e. db to db+4 (e.g. 6, 7, 8, 9, 10)
```

In `/etc/valkey/valkey.conf` search for the lines conceding user access and add the line:
```
user affine    on  +@all ~* &*    >kjdkfjdjfdjfdjfadjfjdasf
```
Don't forget to restart your redis/valkey service
