### ISSUE TITLE
[Bug]: selfhosted beta result in JSON error 404 RESOURCE_NOT_FOUND

### ISSUE THREAD

**Issue by ricky-rebo** [toeverything/AFFiNE#11470]
### What happened?

I freshly installed an instance of selfhosted AFFiNE with `beta` revision.

The service started successfully, but if i try to access the web interface it results in the following error

![Image](https://github.com/user-attachments/assets/b7e7f894-d8ea-4404-a0b4-94e8ed1e8d72)

For every page i try to access (index, /admin, ...)

The instance is running behind Nginx reverse proxy, I already configured the host with Websocket Support.

Any idea if I'm doing something wrong or if there is an actual problem?

- Compose file: 
```yaml
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    restart: unless-stopped
    container_name: affine_server
    ports:
      - '${AFFINE_SERVER_PORT:-3010}:3010'
    volumes:
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    depends_on:
      affine_migration:
        condition: service_completed_successfully
    environment:
      - AFFINE_SERVER_HOST=${AFFINE_SERVER_HOST}
      - AFFINE_SERVER_HTTPS=${AFFINE_SERVER_HTTPS:-false}
      - AFFINE_SERVER_EXTERNAL_URL=${AFFINE_SERVER_EXTERNAL_URL}
      - REDIS_SERVER_HOST=${REDIS_HOST}
      - REDIS_SERVER_PASSWORD=${REDIS_PASSWORD}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_DATABASE:-affine}
      - MAILER_HOST=${MAILER_HOST}
      - MAILER_PORT=${MAILER_PORT}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SENDER=${MAILER_SENDER}

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - AFFINE_SERVER_HOST=${AFFINE_SERVER_HOST}
      - AFFINE_SERVER_HTTPS=${AFFINE_SERVER_HTTPS:-false}
      - AFFINE_SERVER_EXTERNAL_URL=${AFFINE_SERVER_EXTERNAL_URL}
      - REDIS_SERVER_HOST=${REDIS_HOST}
      - REDIS_SERVER_PASSWORD=${REDIS_PASSWORD}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT:-5432}/${DB_DATABASE:-affine}
```

- Env:
```env
UPLOAD_LOCATION=/services/affine/storage
CONFIG_LOCATION=/services/affine/config
AFFINE_SERVER_HOST=***
AFFINE_SERVER_HTTPS=true
AFFINE_SERVER_EXTERNAL_URL=***
REDIS_HOST=192.168.25.16
DB_HOST=192.168.25.17
DB_DATABASE=affine
DB_USERNAME=affine
DB_PASSWORD=***
REDIS_PASSWORD=***
AFFINE_REVISION=beta
MAILER_HOST=***
MAILER_PORT=465
MAILER_USER=***
MAILER_PASSWORD=***
MAILER_SENDER=***
```
(i obviously obsured sensible env variables)

Redis and Postgres are external services in my network, and it's confirmed that tey're up and running.

### Distribution version

Beta Web (https://insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [x] Yes

### Self-hosting Version

beta (0.21.0-beta2)

### Relevant log output

```shell

```
