### ISSUE TITLE
Affine Canary | Docker-Compose Setup leads to 404 Ressource not found

### ISSUE THREAD

**Issue by HoodOG1** [toeverything/AFFiNE#11503]
# Docker-Compose Setup leads to 404 Ressource not found
I am currently trying to start a new compose stack based on the latest version of canary. Somehow however, the webpage itself doesn't seem to be accessable.

I tried it with my main stack also, leads to the same problem. A fresh stack also shows that behavior, am i missing something?

The last canary image, which ran perfectly fine was **sha256:fd4fe09bde2ad053972847a622e9e46b58339b1e5d5bc75ad28c6ad8e45a38f1**

# Images
![Image](https://github.com/user-attachments/assets/4420b8c2-cb37-4589-ac54-fde79a57c53f)

# Compose-File
```yaml
name: affine2
services:
  affine2:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_server2
    ports:
      - '${PORT:-3011}:3010'
    depends_on:
      redis2:
        condition: service_healthy
      postgres2:
        condition: service_healthy
      affine_migration2:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    environment:
      - REDIS_SERVER_HOST=redis2
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres2:5432/${DB_DATABASE:-affine}
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.70

  affine_migration2:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job2
    volumes:
      # custom configurations
      - affine-storage:/root/.affine/storage
      - affine-config:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment:
      - REDIS_SERVER_HOST=redis2
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres2:5432/${DB_DATABASE:-affine}
    depends_on:
      postgres2:
        condition: service_healthy
      redis2:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.20.0.71

  redis2:
    image: redis
    container_name: redis-2
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.72

  postgres2:
    image: pgvector/pgvector:pg16
    container_name: postgres2
    volumes:
      - affine-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # you better set a password for you database
      # or you may add 'POSTGRES_HOST_AUTH_METHOD=trust' to ignore postgres security policy
      # POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.20.0.73

networks:
  default:
    name: <redacted>Network
    external: true

volumes:
  affine-db-data:
  affine-storage:
  affine-config:
```
