### ISSUE TITLE
[Bug]: unable to see history version

### ISSUE THREAD

**Issue by cex-trader** [toeverything/AFFiNE#12325]
### What happened?

request:
/api/workspaces/c0685860-91a7-4f37-983b-d86d2f43dec1/docs/6dg6jq-TuN_5XFDGZieaG/histories/2025-05-16T03:41:43.434Z

responese:
```
{
    "status": 500,
    "code": "Internal Server Error",
    "type": "INTERNAL_SERVER_ERROR",
    "name": "INTERNAL_SERVER_ERROR",
    "message": "An internal error occurred."
}
```

### Distribution version

macOS x64 (Intel)

### App Version

web

### What browsers are you seeing the problem on if you're using web version?

chrome

### Are you self-hosting?

- [x] Yes

### Self-hosting Version

0.17.3

### Relevant log output

```shell
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  | PrismaClientKnownRequestError: 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  |     at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)
affine_selfhosted  |     at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)
affine_selfhosted  |     at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
affine_selfhosted  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
affine_selfhosted  |     at async PermissionService.tryCheckPage (file:///app/dist/core/workspaces/permission.js:288:27)
affine_selfhosted  |     at async PermissionService.checkPagePermission (file:///app/dist/core/workspaces/permission.js:267:15)
affine_selfhosted  |     at async WorkspacesController.history (file:///app/dist/core/workspaces/controller.js:94:9)
affine_selfhosted  |     at async desc.value (file:///app/dist/fundamentals/metrics/utils.js:24:24)
affine_postgres    | 2025-05-16 07:47:34.623 UTC [71] ERROR:  column workspace_page_user_permissions.id does not exist at character 30
affine_postgres    | 2025-05-16 07:47:34.623 UTC [71] STATEMENT:  SELECT COUNT(*) FROM (SELECT "public"."workspace_page_user_permissions"."id" FROM "public"."workspace_page_user_permissions" WHERE ("public"."workspace_page_user_permissions"."workspace_id" = $1 AND "public"."workspace_page_user_permissions"."page_id" = $2 AND "public"."workspace_page_user_permissions"."user_id" = $3 AND "public"."workspace_page_user_permissions"."accepted" = $4 AND "public"."workspace_page_user_permissions"."type" >= $5) OFFSET $6) AS "sub"
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:47:34 AM   ERROR [ExceptionsHandler] 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  | PrismaClientKnownRequestError: 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  |     at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)
affine_selfhosted  |     at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)
affine_selfhosted  |     at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
affine_selfhosted  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
affine_selfhosted  |     at async PermissionService.tryCheckPage (file:///app/dist/core/workspaces/permission.js:288:27)
affine_selfhosted  |     at async PermissionService.checkPagePermission (file:///app/dist/core/workspaces/permission.js:267:15)
affine_selfhosted  |     at async WorkspacesController.history (file:///app/dist/core/workspaces/controller.js:94:9)
affine_selfhosted  |     at async desc.value (file:///app/dist/fundamentals/metrics/utils.js:24:24)
affine_postgres    | 2025-05-16 07:47:55.250 UTC [71] ERROR:  column workspace_page_user_permissions.id does not exist at character 30
affine_postgres    | 2025-05-16 07:47:55.250 UTC [71] STATEMENT:  SELECT COUNT(*) FROM (SELECT "public"."workspace_page_user_permissions"."id" FROM "public"."workspace_page_user_permissions" WHERE ("public"."workspace_page_user_permissions"."workspace_id" = $1 AND "public"."workspace_page_user_permissions"."page_id" = $2 AND "public"."workspace_page_user_permissions"."user_id" = $3 AND "public"."workspace_page_user_permissions"."accepted" = $4 AND "public"."workspace_page_user_permissions"."type" >= $5) OFFSET $6) AS "sub"
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:47:55 AM   ERROR [ExceptionsHandler] 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  | PrismaClientKnownRequestError: 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  |     at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)
affine_selfhosted  |     at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)
affine_selfhosted  |     at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
affine_selfhosted  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
affine_selfhosted  |     at async PermissionService.tryCheckPage (file:///app/dist/core/workspaces/permission.js:288:27)
affine_selfhosted  |     at async PermissionService.checkPagePermission (file:///app/dist/core/workspaces/permission.js:267:15)
affine_selfhosted  |     at async WorkspacesController.history (file:///app/dist/core/workspaces/controller.js:94:9)
affine_selfhosted  |     at async desc.value (file:///app/dist/fundamentals/metrics/utils.js:24:24)
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:48:07 AM VERBOSE [CacheInterceptor] cache blobs:c0685860-91a7-4f37-983b-d86d2f43dec1 hit
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:49:08 AM VERBOSE [CacheInterceptor] cache blobs:c0685860-91a7-4f37-983b-d86d2f43dec1 hit
affine_postgres    | 2025-05-16 07:49:46.201 UTC [71] ERROR:  column workspace_page_user_permissions.id does not exist at character 30
affine_postgres    | 2025-05-16 07:49:46.201 UTC [71] STATEMENT:  SELECT COUNT(*) FROM (SELECT "public"."workspace_page_user_permissions"."id" FROM "public"."workspace_page_user_permissions" WHERE ("public"."workspace_page_user_permissions"."workspace_id" = $1 AND "public"."workspace_page_user_permissions"."page_id" = $2 AND "public"."workspace_page_user_permissions"."user_id" = $3 AND "public"."workspace_page_user_permissions"."accepted" = $4 AND "public"."workspace_page_user_permissions"."type" >= $5) OFFSET $6) AS "sub"
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:49:46 AM   ERROR [ExceptionsHandler] 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  | PrismaClientKnownRequestError: 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  |     at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)
affine_selfhosted  |     at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)
affine_selfhosted  |     at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
affine_selfhosted  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
affine_selfhosted  |     at async PermissionService.tryCheckPage (file:///app/dist/core/workspaces/permission.js:288:27)
affine_selfhosted  |     at async PermissionService.checkPagePermission (file:///app/dist/core/workspaces/permission.js:267:15)
affine_selfhosted  |     at async WorkspacesController.history (file:///app/dist/core/workspaces/controller.js:94:9)
affine_selfhosted  |     at async desc.value (file:///app/dist/fundamentals/metrics/utils.js:24:24)
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:50:09 AM VERBOSE [CacheInterceptor] cache blobs:c0685860-91a7-4f37-983b-d86d2f43dec1 hit
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:51:10 AM VERBOSE [CacheInterceptor] cache blobs:c0685860-91a7-4f37-983b-d86d2f43dec1 hit
affine_postgres    | 2025-05-16 07:51:37.226 UTC [71] ERROR:  column workspace_page_user_permissions.id does not exist at character 30
affine_postgres    | 2025-05-16 07:51:37.226 UTC [71] STATEMENT:  SELECT COUNT(*) FROM (SELECT "public"."workspace_page_user_permissions"."id" FROM "public"."workspace_page_user_permissions" WHERE ("public"."workspace_page_user_permissions"."workspace_id" = $1 AND "public"."workspace_page_user_permissions"."page_id" = $2 AND "public"."workspace_page_user_permissions"."user_id" = $3 AND "public"."workspace_page_user_permissions"."accepted" = $4 AND "public"."workspace_page_user_permissions"."type" >= $5) OFFSET $6) AS "sub"
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:51:37 AM   ERROR [ExceptionsHandler] 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  | PrismaClientKnownRequestError: 
affine_selfhosted  | Invalid `prisma.workspacePageUserPermission.count()` invocation:
affine_selfhosted  | 
affine_selfhosted  | 
affine_selfhosted  | The column `workspace_page_user_permissions.id` does not exist in the current database.
affine_selfhosted  |     at In.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6877)
affine_selfhosted  |     at In.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:122:6211)
affine_selfhosted  |     at In.request (/app/node_modules/@prisma/client/runtime/library.js:122:5919)
affine_selfhosted  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:127:11167)
affine_selfhosted  |     at async PermissionService.tryCheckPage (file:///app/dist/core/workspaces/permission.js:288:27)
affine_selfhosted  |     at async PermissionService.checkPagePermission (file:///app/dist/core/workspaces/permission.js:267:15)
affine_selfhosted  |     at async WorkspacesController.history (file:///app/dist/core/workspaces/controller.js:94:9)
affine_selfhosted  |     at async desc.value (file:///app/dist/fundamentals/metrics/utils.js:24:24)
affine_selfhosted  | [Nest] 133  - 05/16/2025, 7:52:11 AM VERBOSE [CacheInterceptor] cache blobs:c0685860-91a7-4f37-983b-d86d2f43dec1 hit
```

**Comment by forehalo** [comment]
it looks like your DB migration version is higher then your server version. could you please try to upgrade to the latest?

**Comment by cex-trader** [comment]
> it looks like your DB migration version is higher then your server version. could you please try to upgrade to the latest?

here is my docker-compose
```
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable-6e9db76
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - ./config/.env:/root/.affine/config/.env
      - ./backend-wiki-data/config:/root/.affine/config
      # blob storage
      - ./backend-wiki-data/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '500m'
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:awesome@postgres:5432/affine
      - NODE_ENV=production
  redis:
    image: redis:6.2.6
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - ./backend-wiki-data/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:14.1
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - ./backend-wiki-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: awesome
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata

```
