### ISSUE TITLE
[Bug]: OIDC - claim_name is not used to register user display name

### ISSUE THREAD

**Issue by Zepmann** [toeverything/AFFiNE#12901]
### What happened?

I configured AFFiNE to authenticate with an OIDC provider (Authelia). Authentication is performed successfully and I can see that Authelia provides proper claims when the userinfo endpoint is accessed by sniffing the HTTP traffic between reverse proxy and Authelia. However, despite the claim "name" containing the user's full name, it is not used as the display name by AFFiNE.

What I would like is that the user's name is used as a display name when it is provided by an OIDC claim. AFFiNE already has the configuration parameters for this, but it seems that they are not used. That is why I classify this as a bug and not as a feature request, because it seems like this should be supported.

AFFiNE OIDC config:
``` json
{
  "args":
    {
      "scope":"openid profile email offline_access",
      "claim_id":"preferred_username",
      "claim_name":"name",
      "claim_email":"email"
    },
  "issuer":"https://auth.example.com",
  "clientId":"(clientId removed)",
  "clientSecret":"(clientSecret removed)"
}
```

Authelia OIDC configuration:
``` yml
identity_providers:
  oidc:
    clients:
    -
      client_name: 'Affine'
      client_id: '(client_id removed)'
      client_secret: '(client_secret removed)'
      public: false
      authorization_policy: 'two_factor'
      redirect_uris:
        - 'https://notes.example.com/oauth/callback'
      scopes:
        - 'openid'
        - 'profile'
        - 'email'
        - 'offline_access'
      grant_types:
        - 'authorization_code'
        - 'refresh_token'
      token_endpoint_auth_method: 'client_secret_post'
```

### Distribution version

Web (https://app.affine.pro)

### App Version

v0.22.4

### What browsers are you seeing the problem on if you're using web version?

Firefox

### Are you self-hosting?

- [x] Yes

### Self-hosting Version

v0.22.4

### Relevant log output

```shell

```
