### ISSUE TITLE
shadow style css

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2127]
```css
/*effect style*/ 

.light-menu {
  box-shadow: 0px 0px 12px rgba(66, 65, 73, 0.1), inset 0px 0px 0px rgba(227, 227, 228, 1);
}
.light-shadow-1 {
  box-shadow: 0px 0px 4px rgba(66, 65, 73, 0.1);
}
.light-floatbuttonshadow {
  box-shadow: 0px 1px 16px rgba(0, 0, 0, 0.1), 0px 2px 3px rgba(0, 0, 0, 0.1);
}
.light-popupshadow {
  box-shadow: 0px 0px 24px rgba(0, 0, 0, 0.2), 0px 0px 4px rgba(0, 0, 0, 0.6), inset 0px 0px 0px rgba(227, 226, 228, 1);
}
.dark-menu {
  box-shadow: 0px 0px 12px rgba(0, 0, 0, 1), inset 0px 0px 0px rgba(46, 46, 46, 1);
}
.dark-shadow-1 {
  box-shadow: 0px 0px 4px rgba(20, 20, 20, 1);
}
.dark-popupshadow {
  box-shadow: 0px 0px 26px rgba(0, 0, 0, 0.8), 0px 0px 10px rgba(0, 0, 0, 1), inset 0px 0px 0px rgba(46, 46, 46, 1);
}
.dark-floatbuttonshadow {
  box-shadow: 0px 1px 16px rgba(0, 0, 0, 1), 0px 2px 3px rgba(0, 0, 0, 1);
}
```
