### ISSUE TITLE
AFFiNE client supports connecting selfhosted server

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2646]
Desktop client will support connecting to selfhost servers.

This requires some work and We can't give you a specific time, but it may be included in our next major release.

**Comment by NeoHuncho** [comment]
Any news on the progress of this issue?

**Comment by mwhui** [comment]
是否可以自建云同步而不使用affine clound来同步呢？

**Comment by mwhui** [comment]
is it possible to build my own cloud synchronization instead of using affine cloud for synchronization?

**Comment by LivioGama** [comment]
@mwhui if I'm not wrong, it's already the case, although I also find the wording confusing 😅  [See here](https://docs.affine.pro/docs/self-host-affine#:~:text=you%20must%20login%20to%20your%20self-hosted%20AFFiNE%20Cloud%20to%20store%20your%20data%20into%20the%20database)

**Comment by EYHN** [comment]
@LivioGama @mwhui Actually your selfhost affine has nothing to do with affine cloud. 

All sync and account information are on the selfhost server.

I will adjust the wording of this document.

**Comment by the-chain-gamer** [comment]
this isn't completed yet, right? I cannot find a way to get my desktop client connecting to my docker instance.

**Comment by NeoHuncho** [comment]
Correct, it is not completed yet

**Comment by Felitendo** [comment]
I hope this gets added soon

**Comment by AndyPro720** [comment]
It's been around a year now, should be around the corner!

**Comment by richie80** [comment]
this would be great!

**Comment by easaw** [comment]
Looking forward too it!

I looked at AFFiNE a while back and seeing this has made me want to try it again :)

**Comment by HansAndreManfredson** [comment]
The web client is very capable, so there is no reason to don't give it a try!
I am using selfhosted AFFine and stopped using Logseq for it.

**Comment by almereyda** [comment]
Does this web client allow to collaborate with other people? And would you know how and where it persists its data?

Where do we find it to give it a try?

**Comment by xibidix** [comment]
I found an introduction to Affine online and really like its features! So I decided to deploy it locally, but I'm not a professional. I tried many operations, and due to network issues in China, pulling the images also had problems. However, I managed to resolve those.

I have tried deploying it on both Synology NAS and the company's server, but I haven't succeeded even once.

The failure is manifested in that when I open http://localhost:3010 in my local network, there is no response. However, the Docker container shows that it is running normally. I have tried various methods through BTpanel, 1panel, Container Manager, and Portainer, but none of them worked.

I am close to giving up on deploying Affine locally as I have not been successful.

I referred to https://docs.affine.pro/docs/self-host-affine for deploying Docker.

Below is the YAML configuration for the deployment.

I hope to find a solution and successfully deploy it.


This is the running log of affine_selfhosted

`services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_selfhosted
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    ports:
      - '3010:3010'
      - '5555:5555'
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - /volume2/docker/affine/config:/root/.affine/config
      # blob storage
      - /volume2/docker/affine/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '1000m'
    restart: unless-stopped
    environment:
      # - NODE_OPTIONS="--import=./scripts/register.js"
      - NODE_OPTIONS="--es-module-specifier-resolution=node"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=123456@163.com
      - AFFINE_ADMIN_PASSWORD=a123456
  redis:
    image: redis:latest
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - /volume2/docker/affine/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - /volume2/docker/affine/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U affine']
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata
`


This is the running log of affine_selfhosted.
`
running predeploy script.
yarn run v1.22.22
$ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
$ /app/node_modules/.bin/prisma migrate deploy
Error: request to https://binaries.prisma.sh/all_commits/393aa359c9ad4a4bb28630fb5613f9c281cde053/debian-openssl-3.0.x/schema-engine.sha256 failed, reason: 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:internal/errors:984
  const err = new Error(message);
              ^
Error: Command failed: yarn predeploy
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at runPredeployScript (file:///app/scripts/self-host-predeploy.js:67:3)
    at file:///app/scripts/self-host-predeploy.js:75:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
      
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19,
  stdout: null,
  stderr: null
}
Node.js v20.16.0
running predeploy script.
yarn run v1.22.22
$ yarn prisma migrate deploy && node --import ./scripts/register.js ./dist/data/index.js run
$ /app/node_modules/.bin/prisma migrate deploy

`

This is the running log of affine_redis.
`
1:C 03 Sep 2024 06:50:02.713 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:C 03 Sep 2024 06:50:02.713 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Sep 2024 06:50:02.713 * Redis version=7.4.0, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Sep 2024 06:50:02.713 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 03 Sep 2024 06:50:02.714 * monotonic clock: POSIX clock_gettime
1:M 03 Sep 2024 06:50:02.715 * Running mode=standalone, port=6379.
1:M 03 Sep 2024 06:50:02.715 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 03 Sep 2024 06:50:02.715 * Server initialized
1:M 03 Sep 2024 06:50:02.716 * Loading RDB produced by version 7.4.0
1:M 03 Sep 2024 06:50:02.716 * RDB age 35 seconds
1:M 03 Sep 2024 06:50:02.716 * RDB memory usage when created 0.93 Mb
1:M 03 Sep 2024 06:50:02.716 * Done loading RDB, keys loaded: 1, keys expired: 0.
1:M 03 Sep 2024 06:50:02.716 * DB loaded from disk: 0.000 seconds
1:M 03 Sep 2024 06:50:02.716 * Ready to accept connections tcp
1:M 03 Sep 2024 07:07:19.847 * 100 changes in 300 seconds. Saving...
1:M 03 Sep 2024 07:07:19.847 * Background saving started by pid 624
624:C 03 Sep 2024 07:07:20.149 * DB saved on disk
624:C 03 Sep 2024 07:07:20.149 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 03 Sep 2024 07:07:20.250 * Background saving terminated with success
1:M 03 Sep 2024 07:25:10.568 * 100 changes in 300 seconds. Saving...
1:M 03 Sep 2024 07:25:10.568 * Background saving started by pid 1227
1227:C 03 Sep 2024 07:25:10.845 * DB saved on disk
1227:C 03 Sep 2024 07:25:10.846 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 03 Sep 2024 07:25:10.871 * Background saving terminated with success
1:M 03 Sep 2024 07:42:19.937 * 100 changes in 300 seconds. Saving...
1:M 03 Sep 2024 07:42:19.938 * Background saving started by pid 1831
1831:C 03 Sep 2024 07:42:20.232 * DB saved on disk
1831:C 03 Sep 2024 07:42:20.232 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 03 Sep 2024 07:42:20.241 * Background saving terminated with success
`

这是affine_postgres运行日志
`
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-09-03 06:50:04.944 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-09-03 06:50:04.952 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-09-03 06:50:04.952 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-09-03 06:50:05.047 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-09-03 06:50:05.148 UTC [29] LOG:  database system was shut down at 2024-09-03 06:49:28 UTC
2024-09-03 06:50:05.242 UTC [1] LOG:  database system is ready to accept connections
2024-09-03 06:55:05.219 UTC [27] LOG:  checkpoint starting: time
2024-09-03 06:55:05.766 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.142 s, total=0.548 s; sync files=2, longest=0.075 s, average=0.071 s; distance=0 kB, estimate=0 kB; lsn=0/19539E0, redo lsn=0/19539A8
`

**Comment by SINCHOU** [comment]
> ## Issue Status: 🏗 In Progress
> ![](https://camo.githubusercontent.com/aa0efcfc0fdc52328c985454bbaab33d07dfc6f5d14c8e435c0d8317992bc052/68747470733a2f2f69737375652d626f742e746f65766572797468696e672e776f726b6572732e6465762f7374617469632f73746570732f332e737667)
> 
> **🏗 In Progress**
> 
> We’re currently working on the issue.
> 
> This is an automatic reply by the bot.

How about the progress
Really want to use the multi tab feature on desktop client

**Comment by ouchuji** [comment]
Any news on the progress of this issue?

**Comment by captorxxv** [comment]
any news ?

**Comment by forehalo** [comment]
follow up:

We're currently refactoring the code, one of which tasks is adding support for server settings. This is a prerequisite for enabling clients to connect to self-hosted instances.

**Comment by somnifex** [comment]
Time flies, looking forward to the refactored client

**Comment by your-color** [comment]
I am looking forward to it!

**Comment by amrit92** [comment]
Eagerly waiting to try this out!

**Comment by Nikita-Ma** [comment]
+ Eagerly waiting to try this out!

**Comment by LIHAQ** [comment]
I am looking forward to it!

**Comment by schromp** [comment]
Suggestion: Use this as a "Im waiting for this and am excited about it" button (by reacting).

I follow this post so i can see progress and the last few comments generated quite some noise.

**Comment by izmarel** [comment]
Eagerly waiting for this too. For me this feature has been the main blocker for starting to adopt Affine on a daily basis for drafting and documentation as I want to keep my data synced to my own server instance. Looking forward to it.

**Comment by larrydewey** [comment]
Any additional update on this? It looks like the original release was slotted to be included in `0.7`, but Affine has recently release `0.18.1`. Did this fall through the cracks?

**Comment by AndyPro720** [comment]
Honestly, if you look at affine selfhosted version, it lags a lot behind the release and in support. If you're planning to self-host primarily, in my opinion, better to look for alternatives.

**Comment by JokerQyou** [comment]
> Honestly, if you look at affine selfhosted version, it lags a lot behind the release and in support. If you're planning to self-host primarily, in my opinion, better to look for alternatives.

For support it surely is, I think it's reasonable, since AFFiNE is still in active development, most developer manpower is probably invested to coding rather than documentation or support. However the docker image is not lagging too much. Take the current version which is referenced by [the official docker-compose file](https://github.com/toeverything/AFFiNE/blob/canary/.github/deployment/self-host/compose.yaml):

![image](https://github.com/user-attachments/assets/ac329145-9608-4f34-8a7a-379389bb6f99)

which is exactly the version released yesterday:

![image](https://github.com/user-attachments/assets/8cf0843b-5f75-492b-9327-f1c7243ef0ed)

**Comment by forehalo** [comment]
good news, 0.19.0 will make it available to connect your selfhost instances in desktop apps

**Comment by vishalkrv** [comment]
Thanks @forehalo 

Found this commit in [0.19.0-canary.1](https://github.com/toeverything/AFFiNE/releases/tag/v0.19.0-canary.1) which enables the custom server approach for syc: https://github.com/toeverything/AFFiNE/commit/1fa1a95c10799879bdbd64ecc52f843ae8ec1128

**Comment by captorxxv** [comment]
Just tested with latest 0.19.0 and it works, i can connect to my own instance !!!

**Comment by nooz** [comment]
could someone define the steps to connect to local instance please? it is not immediately clear where and how to do this. thank you.

**Comment by AndyPro720** [comment]
Let the 0.19.0 release, simply pull it, and download the latest app. There's a straightforward option to connect them in the app. If you wish to do it now, you can use the canary release, but it may have quite a few bugs.

**Comment by Timtaran** [comment]
> could someone define the steps to connect to local instance please? it is not immediately clear where and how to do this. thank you.

Simply enable `Multiple Cloud Servers` in the plugins tab in the settings
I'm not sure is it working well because I have stable version of affine on my server and I cannot see any workspaces in affine canary app

**Comment by ATPs** [comment]
any one succesful sync with self-hosted server? I can log in but not viewing the workspaces. failed in creating new workspaces from the client

**Comment by AtlasYang** [comment]
> > could someone define the steps to connect to local instance please? it is not immediately clear where and how to do this. thank you.
> 
> Simply enable `Multiple Cloud Servers` in the plugins tab in the settings I'm not sure is it working well because I have stable version of affine on my server and I cannot see any workspaces in affine canary app

I tried this method and got the same result. However, in the web app of my self-hosted instance, I can see the workspace created in the desktop app, but it doesn't appear in the desktop app itself.

**Comment by almereyda** [comment]
> I'm not sure is it working well because I have stable version of affine on my server and I cannot see any workspaces in affine canary app

For reference, this is the configuration with Traefik sitting in an external `web` network that I came up with when trying to match the server version `canary-cc21742`with the commit of the canary app release `v0.19.0-canary.3`.

<details><summary>compose.yml</summary>
<p>

```yml
networks:
  internal:
  web:
    external: true

x-environment: &environment 
  - NODE_ENV=production
  - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-affine}
  - AFFINE_SERVER_EXTERNAL_URL
  - ENABLE_TELEMETRY=false

  - MAILER_HOST
  - MAILER_PORT
  - MAILER_USER
  - MAILER_PASSWORD
  - MAILER_SENDER
  - MAILER_SECURE

#  - OAUTH_OIDC_ISSUER
#  - OAUTH_OIDC_CLIENT_ID
#  - OAUTH_OIDC_CLIENT_SECRET
#  - OAUTH_OIDC_SCOPE
#  - OAUTH_OIDC_CLAIM_MAP_USERNAME
#  - OAUTH_OIDC_CLAIM_MAP_EMAIL
#  - OAUTH_OIDC_CLAIM_MAP_NAME

  - REDIS_SERVER_HOST
  - REDIS_SERVER_PORT
  - REDIS_SERVER_USER
  - REDIS_SERVER_PASSWORD
  - REDIS_SERVER_DATABASE


services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    environment: *environment
    restart: unless-stopped
    networks:
      - web
      - internal
    labels:
      traefik.enable: true
      traefik.http.services.io-allmende-affine.loadbalancer.server.port: "3010"
      traefik.http.routers.io-allmende-affine-web.entrypoints: web
      traefik.http.routers.io-allmende-affine-web.rule: Host(`${FQDN}`)
      traefik.http.routers.io-allmende-affine-web.middlewares: http-to-https
      traefik.http.middlewares.http-to-https.redirectscheme.scheme: https
      traefik.http.middlewares.http-to-https.redirectscheme.permanent: true
      traefik.http.routers.io-allmende-affine-webs.entrypoints: webs
      traefik.http.routers.io-allmende-affine-webs.rule: Host(`${FQDN}`)
      traefik.http.routers.io-allmende-affine-webs.tls: true
      traefik.http.routers.io-allmende-affine-webs.tls.certresolver: le


  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    environment: *environment
    depends_on:
      postgres:
        condition: service_healthy
    networks: ["web"]

  redis:
    image: redis:7-alpine
    command: '--save 60 1000 --appendonly yes --requirepass "${REDIS_SERVER_PASSWORD}"'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli --pass "$${REDIS_SERVER_PASSWORD}" ping | grep PONG']
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 3s
    environment:
      - REDIS_SERVER_USER
      - REDIS_SERVER_PASSWORD
    volumes:
      - ${REDIS_DATA_LOCATION}:/data
    networks: ["web"]

  postgres:
    image: postgres:16-alpine
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_INITDB_ARGS=--data-checksums
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '$${POSTGRES_USER}', '-d', '$${POSTGRES_DATABASE:-affine}']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: ["web"]
```

</p>
</details> 

<details><summary>.env</summary>
<p>

```sh
FQDN=affine.example.org

# select a revision to deploy, available values: stable, beta, canary
#AFFINE_REVISION=stable
# AFFINE_REVISION=v0.19.0-canary.3 does not exist as OCI image tag
# https://github.com/toeverything/AFFiNE/releases/tag/v0.19.0-canary.3
# cc217425db0f54a1bebed67a33c764ee2dec5478
AFFINE_REVISION=canary-cc21742

# database credentials
POSTGRES_USER=org-example-affine
POSTGRES_PASSWORD=<openssl rand -base64 48>
POSTGRES_DB=org-example-affine

# position of the redis data to persist
REDIS_DATA_LOCATION=/data/bases/redis/affine.example.org
# position of the database data to persist
DB_DATA_LOCATION=/data/bases/postgres/affine.example.org
# position of the upload data(images, files, etc.) to persist
UPLOAD_LOCATION=/data/domains/affine.example.org/.state/storage
# position of the configuration files to persist
CONFIG_LOCATION=/data/domains/affine.example.org/.state/config
# set the port for the server container it will expose the server on
#PORT=3010

# set the host for the server for outgoing links
# AFFINE_SERVER_HTTPS=true
# AFFINE_SERVER_HOST=affine.yourdomain.com
# or 
AFFINE_SERVER_EXTERNAL_URL=https://affine.example.org

MAILER_HOST=mail.example.org
MAILER_PORT=465
MAILER_USER=affine@example.org
MAILER_PASSWORD=
MAILER_SENDER=affine@example.org
MAILER_SECURE=1

#OAUTH_OIDC_ISSUER=
#OAUTH_OIDC_CLIENT_ID=
#OAUTH_OIDC_CLIENT_SECRET=
#OAUTH_OIDC_SCOPE=
#OAUTH_OIDC_CLAIM_MAP_USERNAME=
#OAUTH_OIDC_CLAIM_MAP_EMAIL=
#OAUTH_OIDC_CLAIM_MAP_NAME=

REDIS_SERVER_HOST=redis
REDIS_SERVER_PORT=6379
REDIS_SERVER_USER=default
REDIS_SERVER_PASSWORD=<openssl rand -hex 32>
REDIS_SERVER_DATABASE=1
```

</p>
</details> 

This yielded a working configuration, to which I could register the first administrative user at https://affine.example.org

It was then possible to connect an AFFiNE canary app with the self-hosted server.

The last canary release was retrieved from https://github.com/toeverything/AFFiNE/releases?q=canary&expanded=false with https://github.com/toeverything/AFFiNE/releases/tag/v0.19.0-canary.3 being the latest one. It references commit https://github.com/toeverything/AFFiNE/commit/cc217425db0f54a1bebed67a33c764ee2dec5478 who's short SHA is included in the container images, which are published at [Packages · Toeverything](https://github.com/orgs/toeverything/packages?repo_name=AFFiNE).

They hold a series of canary releases, which can all be related to a specific git commit in the repository. Of which `canary` can always be newer than the last tagged canary pre-release.

- [versions?filters%5Bversion_type%5D=tagged · affine-graphql versions · toeverything](https://github.com/toeverything/AFFiNE/pkgs/container/affine-graphql/versions?filters%5Bversion_type%5D=tagged)
  - [320954767?tag=canary-cc21742 · affine-graphql versions · toeverything](https://github.com/toeverything/AFFiNE/pkgs/container/affine-graphql/320954767?tag=canary-cc21742)
- [versions?filters%5Bversion_type%5D=tagged · affine-front versions · toeverything](https://github.com/toeverything/AFFiNE/pkgs/container/affine-front/versions?filters%5Bversion_type%5D=tagged)
  - [320953545?tag=canary-cc21742 · affine-front versions · toeverything](https://github.com/toeverything/AFFiNE/pkgs/container/affine-front/320953545?tag=canary-cc21742)
  
Would someone be able to reproduce the setup?

One known issues is, that the workspace settings screen doesn't load, neither in App nor Web. There are two ever repeating error messages in the log:

```
[Nest] 1  - 12/17/2024, 9:39:08 PM   ERROR [GraphQL] Internal server error
GraphQLError: Unknown type "QueryChatHistoriesInput".
    at Object.NamedType (/app/node_modules/graphql/validation/rules/KnownTypeNamesRule.js:65:11)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
[Nest] 1  - 12/17/2024, 9:39:08 PM   ERROR [GraphQL] Internal server error
GraphQLError: Cannot query field "copilot" on type "UserType".
    at Object.Field (/app/node_modules/graphql/validation/rules/FieldsOnCorrectTypeRule.js:51:13)
    at Object.enter (/app/node_modules/graphql/language/visitor.js:301:32)
    at Object.enter (/app/node_modules/graphql/utilities/TypeInfo.js:391:27)
    at visit (/app/node_modules/graphql/language/visitor.js:197:21)
    at validate (/app/node_modules/graphql/validation/validate.js:91:24)
    at processGraphQLRequest (/app/node_modules/@apollo/server/dist/cjs/requestPipeline.js:101:61)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async internalExecuteOperation (/app/node_modules/@apollo/server/dist/cjs/ApolloServer.js:644:16)
    at async runHttpQuery (/app/node_modules/@apollo/server/dist/cjs/runHttpQuery.js:135:29)
    at async runPotentiallyBatchedHttpQuery (/app/node_modules/@apollo/server/dist/cjs/httpBatching.js:37:16)
```

No AI API key is provided and AI support has been disabled in the app settings, for which a toggle already existed.
