### ISSUE TITLE
Use frpc got error ​`Error: Forbidden resource` when used cloud service

### ISSUE THREAD

**Issue by aliuq** [toeverything/AFFiNE#5949]
### What happened?

Frp is used for intranet penetration. Affine is deployed on Synology. When the client accesses affine's cloud service, an error message `Error: Forbidden resource` is reported.

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
affine_selfhosted  | [Nest] 119  - 02/28/2024, 7:56:47 PM   ERROR [ExceptionLogger] Error: Forbidden resource
affine_selfhosted  | ForbiddenException: Forbidden resource
affine_selfhosted  | [Nest] 119  - 02/28/2024, 7:56:59 PM   ERROR [ExceptionLogger] Error: Forbidden resource
affine_selfhosted  | ForbiddenException: Forbidden resource
affine_selfhosted  |     at canActivateFn (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:157:23)
affine_selfhosted  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
affine_selfhosted  |     at async target (/app/node_modules/@nestjs/core/helpers/external-context-creator.js:73:31)
affine_selfhosted  |     at async Object.createWorkspace (/app/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)
```

### Anything else?

Link:

```bash
# Request URL
/graphql

# Payload
{"query":"\nmutation createWorkspace {\n  createWorkspace {\n    id\n    public\n    createdAt\n  }\n}","operationName":"createWorkspace"}

# Response
{
    "errors": [
        {
            "message": "Forbidden resource",
            "locations": [
                {
                    "line": 3,
                    "column": 3
                }
            ],
            "path": [
                "createWorkspace"
            ],
            "extensions": {
                "code": "FORBIDDEN",
                "originalError": {
                    "message": "Forbidden resource",
                    "error": "Forbidden",
                    "statusCode": 403
                }
            }
        }
    ],
    "data": null
}
```

docker-compose.yaml
```yaml
services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    container_name: affine_selfhosted
    command:
      - sh
      - -c
      - node ./scripts/self-host-predeploy && node ./dist/index.js
    ports:
      - 3010:3010
      - 15555:5555
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      # custom configurations
      - ./affine/config:/root/.affine/config
      - ./affine/storage:/root/.affine/storage
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgres://affine:affine@postgres:5432/affine
      - NODE_ENV=production
      - AFFINE_ADMIN_EMAIL=${AFFINE_ADMIN_EMAIL}
      - AFFINE_ADMIN_PASSWORD=${AFFINE_ADMIN_PASSWORD}
      - ENABLE_CAPTCHA=false
      - AFFINE_SERVER_HOST=xxxxxxxxxxxxxxxx
      - AFFINE_SERVER_HTTPS=true
  redis:
    image: redis
    container_name: affine_redis
    restart: unless-stopped
    volumes:
      - ./affine/redis:/data
    healthcheck:
      test:
        - CMD
        - redis-cli
        - --raw
        - incr
        - ping
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres
    container_name: affine_postgres
    restart: unless-stopped
    volumes:
      - ./affine/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U affine
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: affine
      POSTGRES_PASSWORD: affine
      POSTGRES_DB: affine
      PGDATA: /var/lib/postgresql/data/pgdata

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!
