### ISSUE TITLE
​OIDC Provider does not use mandatory scope field

### ISSUE THREAD

**Issue by js-0s** [toeverything/AFFiNE#8752]
### What happened?

deploy via docker compose behind https: 
image: ghcr.io/toeverything/affine-graphql:stable (9eece242ca7c) (should be unrelated because the code is unchanged in canary branch)

configure oidc using environment + .env:
```
 affine:
    image: ghcr.io/toeverything/affine-graphql:stable
    command:
      ['sh', '-c', 'node ./scripts/self-host-predeploy && node ./dist/index.js']
    networks:
      affine-net:
      affine-front-net:
        aliases:
          - affine
    depends_on:
      affine_cache:
        condition: service_healthy
      affine_db:
        condition: service_healthy
    volumes:
      # custom configurations
      - ./local_data/affine/config:/root/.affine/config
      # blob storage
      - ./local_data/affine/storage:/root/.affine/storage
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
    restart: unless-stopped
    environment:
      - NODE_OPTIONS="--import=./scripts/register.js"
      - AFFINE_CONFIG_PATH=/root/.affine/config
      - REDIS_SERVER_HOST=cache
      - DATABASE_URL=postgres://affine:affine@db:5432/affine
      - NODE_ENV=production

      - TELEMETRY_ENABLE=false
      - AFFINE_SERVER_HOST=affine.example.com
      - AFFINE_SERVER_HTTPS=true
      - MAIL_HOST=${AFFINE_EMAIL_HOST}
      - MAIL_PORT=${AFFINE_EMAIL_PORT}
      - MAIL_USER=${AFFINE_EMAIL_USERNAME}
      - MAIL_PASSWORD=${AFFINE_EMAIL_PASSWORD}
      - OAUTH_OIDC_ISSUER=${AFFINE_OIDC_ISSUER}
      - OAUTH_OIDC_CLIENT_ID=${AFFINE_OIDC_CLIENT_ID}
      - OAUTH_OIDC_CLIENT_SECRET=${AFFINE_OIDC_CLIENT_SECRET}
      - OAUTH_OIDC_SCOPE=openid email profile offline_access
      - OAUTH_OIDC_CLAIM_MAP_ID=preferred_username
      - OAUTH_OIDC_CLAIM_MAP_EMAIL=email
```

`OAUTH_OIDC_SCOPE offline_access` is a authentik thing to add the refresh_token field, it errors in a similar way if absent, but in this case its 'understandable' why affine needs it

after boot, enable oidc/oauth in the config
```
edit local_data/affine/config/affine.js
uncomment
AFFiNE.use('oauth', {                                                                                                                                         
   providers: { 
     oidc: {
.....
```
restart everything

configure authentik  (the auth provider), create a application, provider, configure the generated values into the .env of the docker-compose.yml (a bit beyond this bug)

navigate to your deployment, login using oidc
expect: login success
actual: internal server error

so far, maybe a misconfig on my side, documentation is really thin/confusing/non-promising on that subject. so i inspect the code. i figured that the `refresh_token` is a mandatory thing this way:

`docker exec -it -u root affine-container-id /bin/bash`
install my favorite editor and add debug output to understand the error.
lets start with the original content on the console:
```
affine-1  | [Nest] 133  - 11/07/2024, 11:49:30 PM   ERROR [HTTP] Internal server error                                                                         
affine-1  | ZodError: [                                                                                                                                        
affine-1  |   {                                                                                                                                                
affine-1  |     "code": "invalid_type",                                                                                                                        
affine-1  |     "expected": "string",                                                                                                                          
affine-1  |     "received": "undefined",                                                                                                                       
affine-1  |     "path": [                                                                                                                                      
affine-1  |       "scope"                                                                                                                                      
affine-1  |     ],                                                                                                                                             
affine-1  |     "message": "Required"                                                                                                                          
affine-1  |   }                                                                                                                                                
affine-1  | ]                                                                                                                                                  
affine-1  |     at get error [as error] (file:///app/node_modules/zod/lib/index.mjs:587:31)                                                                    
affine-1  |     at ZodObject.parse (file:///app/node_modules/zod/lib/index.mjs:692:22)                                                                         
affine-1  |     at OIDCClient.fetch (file:///app/dist/plugins/oauth/providers/oidc.js:47:25)                                                                   
affine-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                  
affine-1  |     at async OIDCClient.token (file:///app/dist/plugins/oauth/providers/oidc.js:85:23)                                                             
affine-1  |     at async OIDCProvider.getToken (file:///app/dist/plugins/oauth/providers/oidc.js:159:16)                                                       
affine-1  |     at async OAuthController.callback (file:///app/dist/plugins/oauth/controller.js:68:24)   
```
dumping the token in question i realize that there is no scope attribute:
```
affine-1  |   url: 'https://auth.example.com/application/o/token/',
affine-1  |   data: {
affine-1  |     access_token: 'ey.......',
affine-1  |     token_type: 'Bearer',
affine-1  |     expires_in: 300,
affine-1  |     id_token: 'ey.....'
affine-1  |   },
```

so my very naive way was: lets remove the scope from the OIDCTokenSchema and see what happens, worst case is that anyone reads that scope and its undefined and crashes again
the modified oidc.js looks like this:
```
const OIDCTokenSchema = z.object({
    access_token: z.string(),
    expires_in: z.number(),
    refresh_token: z.string(),
//    scope: z.string(),
    token_type: z.string(),
});
```
and voila, the auth succeeds, affine is happy and lets the user pass.

but wait, why it was crashing in the first place, what is this scope used for then, why is it mandatory?

So this bug report requests o make the scope field optional (or completely remove it)

according to https://openid.net/specs/openid-connect-core-1_0.html#TokenEndpoint 3.1.3.3.  Successful Token Response:
As specified in [OAuth 2.0](https://openid.net/specs/openid-connect-core-1_0.html#RFC6749) [RFC6749], Clients SHOULD ignore unrecognized response parameters.

https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.4
[4.1.4](https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.4).  Access Token Response

   If the access token request is valid and authorized, the
   authorization server issues an access token and optional refresh
   token as described in [Section 5.1](https://www.rfc-editor.org/rfc/rfc6749.html#section-5.1).  If the request client
   authentication failed or is invalid, the authorization server returns
   an error response as described in [Section 5.2](https://www.rfc-editor.org/rfc/rfc6749.html#section-5.2).

As this is a auth-releated bug, i'd even consider it a (non-critical) security issue and would support others with more oidc expertise to have another read through the existing code (packages/backend/server/src/plugins/oauth/providers/oidc.ts), because if its possible to create a insecure setup this way, boundaries should be enforced to keep good light on this project.

### Distribution version

Linux

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
see above
```

### Anything else?

authentik: https://goauthentik.io/
oidc token rfc: https://www.rfc-editor.org/rfc/rfc6749.html#section-4.1.4

btw: the pieces application code looks readable and clean, great choices of dependencies to compile it!

i had a look in the controller that uses the received token and found a maybe more serious issue, anything that the auth-provider adds to the token will be tried to get stored into the db (`oauth/controller.js:98`):
```
        await this.db.connectedAccount.create({
            data: {
                userId: user.id,
                provider,
                providerAccountId: externalAccount.id,
                ...tokens,
            },
        });
```
which would allow a malicious oauth provider to override userId, provider, providerAccountId (or cause another crash because it tries to store undefined model fields)

**Comment by darkskygit** [comment]
https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/ 
according to the document, scope is not mandatory, but it needs to be provided when the token scope changes
we can change the validation of this field to optional

**Comment by js-0s** [comment]
Thank you for the quick response!
The way i read the document it describes the request-parameters not the response.
The request is compiled in L100 (not the refresh-token-request, just the token-request)
The response is parsed with the OIDCTokenSchema which expects that the token contains the scope field which it does not.

the refresh_token is nicely stored but its never used again. The scope (to be stored along with the refresh_token to allow the feature described in the document) should be set to `this.args?.scope || 'openid profile email',`. specific libraries (eg https://github.com/authts/oidc-client-ts/issues/695) mention that the request scope and the refresh-token-request-scope do not always match so its not that easy unfortunately.

I reviewed the google implementation and the google documentation: https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token#response-body
its a different api (v1/oauth2) and i am not quiet sure why this works there, it should not, In other implementations i reviewed to find a good example there is no explicit check a scope for in responses.

In any way, making the bugfix easy to apply without breaking too much, making the scope optional is the straight forward solution. even if i assume that this wont survive a expert review on that topic. my experience is just auth0/nextauth, mostly relying on 'them' doing things right (and never implementing the refresh-token part myself).

**Comment by darkskygit** [comment]
> Thank you for the quick response! The way i read the document it describes the request-parameters not the response. The request is compiled in L100 (not the refresh-token-request, just the token-request) The response is parsed with the OIDCTokenSchema which expects that the token contains the scope field which it does not.
> 
> the refresh_token is nicely stored but its never used again. The scope (to be stored along with the refresh_token to allow the feature described in the document) should be set to `this.args?.scope || 'openid profile email',`. specific libraries (eg [authts/oidc-client-ts#695](https://github.com/authts/oidc-client-ts/issues/695)) mention that the request scope and the refresh-token-request-scope do not always match so its not that easy unfortunately.
> 
> I reviewed the google implementation and the google documentation: https://cloud.google.com/iam/docs/reference/sts/rest/v1/TopLevel/token#response-body its a different api (v1/oauth2) and i am not quiet sure why this works there, it should not, In other implementations i reviewed to find a good example there is no explicit check a scope for in responses.
> 
> In any way, making the bugfix easy to apply without breaking too much, making the scope optional is the straight forward solution. even if i assume that this wont survive a expert review on that topic. my experience is just auth0/nextauth, mostly relying on 'them' doing things right (and never implementing the refresh-token part myself).

the response doc is on the page containing the aforementioned link: https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/
the scope may change due to the policies or user operation in the oidc provider
for example, if an administrator or user manually revokes some previously granted permissions or granted some new permissions, in this case, the oidc provider response will include the scope field during the refresh

**Comment by Tealk** [comment]
@js-0s did you get the SSO to work? If so, how? I don't see a button for SSO in the login window so that I could start the authentication against authentik.

**Comment by js-0s** [comment]
> @js-0s did you get the SSO to work? If so, how? I don't see a button for SSO in the login window so that I could start the authentication against authentik.
@Tealk the OIDC experience with affine was great. It just worked after the patch.

1. patched the docker-container (because i could not wait for the release): 
  ```
docker exec -it -u root data-affine-1 \
  bash -c " \
    sed -ibackup 's|scope: z\.string(),|scope: z.string().optional(),|' \
      /app/dist/plugins/oauth/providers/oidc.js;\
    "
``` 
and restarted it
2. configured the environment according to authentik. in the process i did read some affine source docs - that was straightforward to add into a docker-compose file:
```
      OAUTH_OIDC_ISSUER: ${AFFINE_OIDC_ISSUER}
      OAUTH_OIDC_CLIENT_ID: ${AFFINE_OIDC_CLIENT_ID}
      OAUTH_OIDC_CLIENT_SECRET: ${AFFINE_OIDC_CLIENT_SECRET}
      OAUTH_OIDC_SCOPE: openid email profile offline_access
      OAUTH_OIDC_CLAIM_MAP_ID: preferred_username
      OAUTH_OIDC_CLAIM_MAP_EMAIL: email
```
i think there was a authentik provider config for the scope, but nothing complicated there.

after that there is a "Continue with OIDC" button on the login page.

**Comment by Tealk** [comment]
I also managed to get it to work with 0.19.5, and I only set the following:


```
// AFFiNE/config/affine.js
OAUTH_OIDC_ISSUER=https://auth.example.com/application/o/affine/
OAUTH_OIDC_CLIENT_ID=CLIENTID
OAUTH_OIDC_CLIENT_SECRET=CLIENTSECRET
OAUTH_OIDC_SCOPE=openid email profile offline_access
OAUTH_OIDC_CLAIM_MAP_ID=preferred_username
OAUTH_OIDC_CLAIM_MAP_EMAIL=email
```


```
// AFFiNE/.env
AFFiNE.use('oauth', {
  providers: {
    authentik: { // I wanted to try whether I could rename the button.
    },
  },
});
```
I didn't touch the docker-compose file.

**Comment by madduck** [comment]
I tried the @js-0s patch, but to no avail. I see the OIDC button, and the Authentik flow is working properly, until things go back to AFFiNE, where the server then reports an error:

```
[Nest] 1  - 01/11/2025, 9:46:46 PM   ERROR [HTTP] Internal server error
ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "refresh_token"
    ],
    "message": "Required"
  }
]
    at get error [as error] (file:///app/node_modules/zod/lib/index.mjs:587:31)
    at ZodObject.parse (file:///app/node_modules/zod/lib/index.mjs:663:22)
    at OIDCClient.fetch (file:///app/dist/plugins/oauth/providers/oidc.js:45:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async OIDCClient.token (file:///app/dist/plugins/oauth/providers/oidc.js:83:23)
    at async OIDCProvider.getToken (file:///app/dist/plugins/oauth/providers/oidc.js:158:16)
    at async OAuthController.callback (file:///app/dist/plugins/oauth/controller.js:68:24)
```

I have added `offline_access` to the scope. And again, this bug is present with or without patching of `/app/dist/plugins/oauth/providers/oidc.js`

The HTTP POST request this relates to is goes to `https://notes.example.org/api/oauth/callback` and the request payload is a JSON dict with two keys, `code` and `state`:

![image](https://github.com/user-attachments/assets/ebd61e0a-6e08-4339-afb9-430c4e8fb915)

**Comment by nhths** [comment]
@madduck I have same problem and resolve it without patch. Try to check available scopes in your provider.

![Image](https://github.com/user-attachments/assets/6a8c6b54-da24-40ec-a763-408ae2d0fceb)

**Comment by bwrsandman** [comment]
For anyone, like me, who is trying the previous comment and setting oauth config through the webapi, you need to [follow the docs](https://docs.affine.pro/self-host-affine/administer/oauth-2-0?utm_source=chatgpt.com#oidc) but then set the args as follows
```
{"args":{"scope":"openid profile email offline_access"}, ...
```

![Image](https://github.com/user-attachments/assets/8803c565-6598-4ddd-884f-44f315ab345d)

Then do what @nhths says: in the authentik provider, add `offline_access` in Advanced Protocol Settings / Scopes

**Comment by elmnic** [comment]
And for anyone trying to use Authelia, I managed to make it work by also adding 
```
        grant_types:
          - 'refresh_token'
          - 'authorization_code'
```
to Authelia's config for the affine client, as per [this reply](https://github.com/authelia/authelia/discussions/8354#discussioncomment-11415742) to make `offline_access` scope work

**Comment by catfishlty** [comment]
Thanks to @bwrsandman and @elmnic 
Based on my testing, combined with their configs, OIDC can connect to Authelia.
## Authelia
```yaml
      - client_name: 'AFFiNE'
        client_id: 'your-affine-client-id'
        client_secret: 'your-affine-client-secret'
        authorization_policy: 'one_factor'
        public: false
        redirect_uris:
          - 'https://affine.example.com/oauth/callback'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'offline_access'
        grant_types:
          - 'refresh_token'
          - 'authorization_code'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
```

## AFFiNE
### Settings -> Server
This is important, it will define the host of OIDC redirect url.
```
https://affine.example.com
```
### Settings -> OAuth -> OIDC OAuth provider config
```json
{"args":{"scope":"openid profile email offline_access","claim_id":"preferred_username","claim_email":"email"},"issuer":"https://auth.example.com","clientId":"your-affine-client-id","clientSecret":"your-affine-client-secret"}
```

I hope it can help.
