### ISSUE TITLE
The historical version is not available.

### ISSUE THREAD

**Issue by pipuwong** [toeverything/AFFiNE#9557]
### What happened?

OS: Linux, Debian12
Desktop App Affine v0.19.5

I really like affine, I even recommend it to the people around me, hoping it gets better. Thank you for your efforts. I self-hosted affine on a server, and a problem occurred.

When I tried to restore the document, I found that the historical versions were not available.
How should I do to use the historical version?

https://github.com/user-attachments/assets/6c56b7ee-fcb3-4b69-a068-ba4c289db5b0

### Distribution version

macOS x64 (Intel)

### Are you self-hosting?

- [x] Yes

**Comment by forehalo** [comment]
any log from your instance server?

**Comment by ApfelQrown** [comment]
Hi,

I have the same issue and I wanted to add more information here. Is it correct to post it here or should I post a new issue?

**My Client:**
Windows 11 Pro 24H2
Affine 0.19.6

**My Server:**
Host OS: Ubuntu 24.04.1 LTS
Docker: 27.4.1
Docker compose: v2.32.1
Traefik v3.2
Runs the stable release and was updated today (22.01.2025)

## Configuration

In the docker-compose.yml I changed a few things so it works with Traefik.
**docker-compose.yml**
```
name: affine

services:
  affine:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_server
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      affine_migration:
        condition: service_completed_successfully
    volumes:
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
    restart: unless-stopped
    networks:
      - proxy
      - internal_affine                                                                                                         
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.affine.entrypoints=websecure"
      - "traefik.http.routers.affine.tls=true"
      - "traefik.http.routers.affine.rule=Host(`affine.example.com`)"
      - "traefik.http.services.affine.loadbalancer.server.port=3010"

  affine_migration:
    image: ghcr.io/toeverything/affine-graphql:${AFFINE_REVISION:-stable}
    container_name: affine_migration_job
    volumes:
      # custom configurations
      - ${UPLOAD_LOCATION}:/root/.affine/storage
      - ${CONFIG_LOCATION}:/root/.affine/config
    command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
    env_file:
      - .env
    environment:
      - REDIS_SERVER_HOST=redis
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE:-affine}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_affine
 
  redis:
    image: redis
    container_name: affine_redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal_affine

  postgres:
    image: postgres:16
    container_name: affine_postgres
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE:-affine}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', "${DB_USERNAME}", '-d', "${DB_DATABASE:-affine}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - internal_affine

networks:
  proxy:
    external: true
  internal_affine:
    internal: true
```

**.env**
```
# select a revision to deploy, available values: stable, beta, canary
AFFINE_REVISION=stable

# set the port for the server container it will expose the server on
PORT=3010

# set the host for the server for outgoing links
AFFINE_SERVER_HTTPS=true
AFFINE_SERVER_HOST=affine.example.com
# or
# AFFINE_SERVER_EXTERNAL_URL=https://affine.example.com

# position of the database data to persist
DB_DATA_LOCATION=./postgres/pgdata
# position of the upload data(images, files, etc.) to persist
UPLOAD_LOCATION=./storage
# position of the configuration files to persist
CONFIG_LOCATION=./config

# database credentials
DB_USERNAME=affine
DB_PASSWORD=SUPER_SECRET_PASSWORD
DB_DATABASE=affine
```

## Logs

The Logs are gathered ~1 min after the failed connection attempt

**affine_server**
```
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Nest] 1  - 01/22/2025, 12:47:12 PM    WARN [MailerModule] MailerModule is not enabled because of the required configuration is not satisfied.
[Nest] 1  - 01/22/2025, 12:47:12 PM    WARN [MailerModule] Unsatisfied configuration:
[Nest] 1  - 01/22/2025, 12:47:12 PM    WARN [MailerModule]   AFFiNE.mailer.host
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [NestFactory] Starting Nest application... +10ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +22ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] GqlModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +8ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] RedisModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] MetricsModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] StorageProviderModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] HelpersModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] ErrorModule dependencies initialized +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] WebSocketModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] EventModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] MailModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] StorageModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] PermissionModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] MutexModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] RuntimeModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] ServerConfigModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] RateLimiterModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] FeatureModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] QuotaModule dependencies initialized +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] SelfhostModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] UserModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] DocStorageModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] SyncModule dependencies initialized +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] DocRendererModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [InstanceLoader] WorkspaceModule dependencies initialized +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:join" message +8ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:leave" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:load-doc" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:delete-doc" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:push-doc-updates" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:push-doc-update" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:load-doc-timestamps" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:join-awareness" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:leave-awareness" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:load-awarenesses" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "space:update-awareness" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "client-handshake-sync" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "client-leave-sync" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "client-pre-sync" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "client-update-v2" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "doc-load-v2" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "client-handshake-awareness" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "client-leave-awareness" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "awareness-init" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [WebSocketsController] SpaceSyncGateway subscribed to the "awareness-update" message +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RoutesResolver] AppController {/info}: +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/info, GET} route +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RoutesResolver] UserAvatarController {/api/avatars}: +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/avatars/:id, GET} route +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RoutesResolver] AuthController {/api/auth}: +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/auth/preflight, POST} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/auth/sign-in, POST} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/auth/sign-out, GET} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/auth/magic-link, POST} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/auth/session, GET} route +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/auth/sessions, GET} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RoutesResolver] WorkspacesController {/api/workspaces}: +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/workspaces/:id/blobs/:name, GET} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/workspaces/:id/docs/:guid, GET} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/workspaces/:id/docs/:guid/histories/:timestamp, GET}  route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RoutesResolver] DocRendererController {/workspace}: +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/workspace/*, GET} route +1ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RoutesResolver] CustomSetupController {/api/setup}: +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [RouterExplorer] Mapped {/api/setup/create-admin-user, POST} route +0ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [DocStorageCronJob] Updates pending queue auto merging cron started
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [GraphQLModule] Mapped {/graphql, POST} route +90ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [NestApplication] Nest application successfully started +24ms
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [App] AFFiNE Server is running in [selfhosted] mode
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [App] Listening on http://0.0.0.0:3010
[Nest] 1  - 01/22/2025, 12:47:12 PM     LOG [App] And the public server should be recognized as https://affine.home.apfel.wtf
[Nest] 1  - 01/22/2025, 12:47:21 PM VERBOSE [Locker] Client cluster:8-6MMMo8kysxKfAMiLimV:Yfo-tMoKKlo3b3KuqcTIO is trying to lock resource doc:update:88420b84-a0a3-4ac4-b9e9-1307e74471de:88420b84-a0a3-4ac4-b9e9-1307e74471de
[Nest] 1  - 01/22/2025, 12:47:21 PM VERBOSE [Locker] Client cluster:8-6MMMo8kysxKfAMiLimV:WytCIUTaXGaV9I8_1CTYf is trying to lock resource doc:update:88420b84-a0a3-4ac4- 9e9-1307e74471de:userdata$297ea4f1-1898-4240-834b-43d34311a8f4$88420b84-a0a3-4ac4-b9e9-1307e74471de$favorite
[Nest] 1  - 01/22/2025, 12:47:21 PM VERBOSE [Locker] Client cluster:8-6MMMo8kysxKfAMiLimV:DBdSXL0RmZ0kHGyERQkee is trying to lock resource doc:update:88420b84-a0a3-4ac4-b9e9-1307e74471de:db$88420b84-a0a3-4ac4-b9e9-1307e74471de$docCustomPropertyInfo
```

**affine_migration_job**
```
running predeploy script.
yarn run v1.22.22
$ yarn prisma migrate deploy && NODE_ENV=script node --import ./scripts/register.js ./dist/data/index.js run
$ /app/node_modules/.bin/prisma migrate deploy
Prisma schema loaded from schema.prisma
Datasource "db": PostgreSQL database "affine", schema "public" at "postgres:5432"

53 migrations found in prisma/migrations


No pending migrations to apply.
(node:143) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[Nest] 143  - 01/22/2025, 12:47:09 PM    WARN [MailerModule] MailerModule is not enabled because of the required configuration is not satisfied.
[Nest] 143  - 01/22/2025, 12:47:09 PM    WARN [MailerModule] Unsatisfied configuration:
[Nest] 143  - 01/22/2025, 12:47:09 PM    WARN [MailerModule]   AFFiNE.mailer.host
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [NestFactory] Starting Nest application... +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] CommandRootModule dependencies initialized +23ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] GqlModule dependencies initialized +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +6ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] DiscoveryModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] EventModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] RedisModule dependencies initialized +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] PrismaModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] MetricsModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] StorageProviderModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] HelpersModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] ErrorModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] WebSocketModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] ScheduleModule dependencies initialized +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] EventEmitterModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] CommandRunnerModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] PermissionModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] MailModule dependencies initialized +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] StorageModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] CliAppModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] ThrottlerModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] CacheModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] MutexModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] RuntimeModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] ServerConfigModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] RateLimiterModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] FeatureModule dependencies initialized +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] QuotaModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] SelfhostModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] UserModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] DocStorageModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] SyncModule dependencies initialized +1ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] DocRendererModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] AuthModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [InstanceLoader] WorkspaceModule dependencies initialized +0ms
[Nest] 143  - 01/22/2025, 12:47:09 PM     LOG [RunCommand] Done 0 migrations
Done in 2.64s.
```

**affine_redis**
```
1:C 22 Jan 2025 12:46:56.297 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 22 Jan 2025 12:46:56.297 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 22 Jan 2025 12:46:56.297 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 22 Jan 2025 12:46:56.297 * monotonic clock: POSIX clock_gettime
1:M 22 Jan 2025 12:46:56.298 * Running mode=standalone, port=6379.
1:M 22 Jan 2025 12:46:56.298 * Server initialized
1:M 22 Jan 2025 12:46:56.298 * Ready to accept connections tcp
1:M 22 Jan 2025 12:51:57.023 * 100 changes in 300 seconds. Saving...
1:M 22 Jan 2025 12:51:57.023 * Background saving started by pid 195
195:C 22 Jan 2025 12:51:57.029 * DB saved on disk
195:C 22 Jan 2025 12:51:57.030 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
1:M 22 Jan 2025 12:51:57.124 * Background saving terminated with success
```

**affine_postgres**
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2025-01-22 12:46:56.319 UTC [1] LOG:  starting PostgreSQL 16.6 (Debian 16.6-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2025-01-22 12:46:56.320 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2025-01-22 12:46:56.320 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2025-01-22 12:46:56.324 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2025-01-22 12:46:56.329 UTC [29] LOG:  database system was shut down at 2025-01-22 11:54:28 UTC
2025-01-22 12:46:56.334 UTC [1] LOG:  database system is ready to accept connections
2025-01-22 12:51:56.369 UTC [27] LOG:  checkpoint starting: time
2025-01-22 12:51:56.694 UTC [27] LOG:  checkpoint complete: wrote 6 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.306 s, sync=0.009 s, total=0.326 s; sync files=4, longest=0.005 s, average=0.003 s; distance=9 kB, estimate=9 kB; lsn=0/3DC4158, redo lsn=0/3DC4120
```
